intake_site/catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('brand/<int:pk>', views.BrandDetailView.as_view(), name='brand-detail'),
	path('',views.index,name='index'),
	#path('login/',views.login,name='login'),
	path('cars/', views.CarListView.as_view(), name='cars'),
	path('car/<int:pk>', views.CarDetailView.as_view(), name='car-detail'),	
	path('brands/', views.BrandListView.as_view(), name='brands'),
	path('signup/', views.SignUp.as_view(), name='signup'),

]

urlpatterns += [
    path('car/create/', views.CarCreate.as_view(), name='car_create'),
    path('car/<int:pk>/update/', views.CarUpdate.as_view(), name='car_update'),
    path('car/<int:pk>/delete/', views.CarDelete.as_view(), name='car_delete'),
]

intake_site/intake_site/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
   # path('', TemplateView.as_view(template_name='home.html'), name='home'),

]

urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

intake_site/catalog/models.py
from django.db import models
from django.urls import reverse
import uuid

# Create your models here.

class Car(models.Model):

	car_brand = models.ForeignKey('Brand', on_delete=models.SET_NULL, null=True)
	car_model = models.CharField(max_length=50, help_text="Ingrese el modelo del auto")
	car_plate = models.IntegerField( primary_key=True, blank=False,default='111111')
	car_price = models.IntegerField(help_text='Ingrese precio estimado de venta')
	car_category = models.CharField(max_length=30,default='---', help_text='Ingrese la categoria/disciplina del vehiculo')
	car_year = models.IntegerField( help_text='Ingrese el año del auto')
	car_engine = models.CharField(max_length=30, default='---', help_text='Ingrese el tipo de motor del vehiculo')
	car_cilindrada = models.FloatField( help_text='Ingrese la cilindrada del motor')

	DriveTrain_STATUS = (
		('4WD', '/Four Wheel Drive / Traccion Integral'),
		('AWD', 'All Wheel Drive / Traccion Total'),
		('FWD', 'Front Wheel Drive / Traccion Delantera'),
		('RWD', 'Rear Whell Drive / Traccion Trasera'),
	)

	car_drivetrain = models.CharField(
		max_length=3, 
		choices=DriveTrain_STATUS,
		blank=False,
		default='---3', 
		help_text='Ingrese la opcion de traccion que posea el vehiculo')

	def __str__(self):
		return self.car_model

	def get_absolute_url(self):
		"""Returns the url to access a detail record for this book."""
		return reverse('car-detail', args=[str(self.car_plate)])



class Brand(models.Model):
	brand_name = models.CharField(max_length=40) 


	class Meta:
		ordering = ['brand_name']

	def get_absolute_url(self):
		return reverse('brand-detail', args=[str(self.id)])

	def __str__(self):
		return self.brand_name

intake_site/catalog/views.py
from django.shortcuts import render
from.models import Brand, Car
from django.views import generic

# Create your views here.
def index(request):
	brands_available=Brand.objects.all().count()
	cars_available=Car.objects.all().count()

	return render(
        request,
        'index.html',
        context={'brands_available':brands_available,'cars_available':cars_available},
    )

class CarListView(generic.ListView):
	model = Car

class CarDetailView(generic.DetailView):
	model = Car

class BrandListView(generic.ListView):
	model = Brand

class BrandDetailView(generic.DetailView):
	model = Brand

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Car

class CarCreate(CreateView):
	model = Car
	fields = '__all__'
	#initial = {'car_model':'',}

class CarUpdate(UpdateView):
	model = Car
	fields = '__all__'

class CarDelete(DeleteView):
	model = Car
	success_url = reverse_lazy('cars')

from django.contrib.auth.forms import UserCreationForm


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

intake_site/catalog/templates/base_generica.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

   {% load static %}
  <title>Intake Fabricantes</title>

  <!-- Custom fonts for this theme -->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css'%}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

  <!-- Theme CSS -->
  <link href="{% static 'css/freelancer.css'%}" rel="stylesheet">

</head>

<body id="page-top">

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="#page-top">Intake</a>
      <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item mx-0 mx-lg-1">
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#portfolio">Fabricantes y Modelos</a>
          </li>
          <li class="nav-item mx-0 mx-lg-1">
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#about">Vende tu Auto!</a>
          </li>
          <li class="nav-item mx-0 mx-lg-1">
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#contact">Contactanos :)</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

intake_site/catalog/templates/catalog/brand_detail.html
{extends "index.html" %}



      
{% block content %}

<h1> Lista de Vehiculos de la marca <a href="{{ brand.get_absolute_url }}">{{ brand.brand_name }}</a></h1>

<div style="margin-left:20px;margin-top:20px">
<h4>Modelos</h4>


    
  {% for car in brand.car_set.all %}
    <dt><a href="{% url 'car-detail' car.pk %}">{{car}}</a> </dt>
    
  

  {% endfor %}


</div>
{% endblock %}


     

intake_site/catalog/templates/catalog/brand_list.html
{ extends "index.html" %}

{% load static %}
	<h1> Lista de Vehiculos </h1>

	{% if brand_list %}
    <ul>

      {% for brand in brand_list %}
      <li>
        <a href="{{ brand.get_absolute_url }}">{{ brand.brand_name }}</a>  
        
      </li>
      {% endfor %}

    </ul>

    {% else %}
      <p>TNo hay Fabricantes diponibles en este momento....</p>
    {% endif %}       

intake_site/catalog/templates/catalog/car_confirm_delete.html
{ extends "base_generic.html" %}

{% block content %}

<h1>Eliminar Vehiculo</h1>

<p>Estas seguro de eliminar el vehiculo: {{ car }} de Intake?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Si, Eliminar." />
</form>

{% endblock %}

intake_site/catalog/templates/catalog/car_detail.html
{ extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ car.car_model}}</h1>

  <p><strong>Marca:</strong> <a href="{% url 'brands' %}">{{ car.car_brand }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Modelo:</strong> {{ car.car_model }}</p>
  <p><strong>Patente:</strong> {{ car.car_plate }}</p> 
  <p><strong>Precio:</strong> {{ car.car_price }}</p>
  <p><strong>Categoria:</strong> {{ car.car_category }}</p>
  <p><strong>Año:</strong> {{ car.car_year }}</p>
  <p><strong>Motor:</strong> {{ car.car_engine }}</p>
  <p><strong>Cilindrada:</strong> {{ car.car_cilindrada }}</p>
  <p><strong>Traccion:</strong> {{ car.car_drivetrain }}</p>  


  
{% endblock %}

intake_site/catalog/templates/catalog/car_form.html
{ extends "base_generic.html" %}

{% block content %}
<h1>Intake: Ingreso De Vehiculo</h1>

  <p>Bienvenido a la seccion de  <em>Ventas</em>, Intake! </p>

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Ingresar" />
    
</form>
{% endblock %}

intake_site/catalog/templates/catalog/car_list.html
{ extends "index.html" %}

{% load static %}
	<h1> Lista de Vehiculos </h1>

	{% if car_list %}
    <ul>

      {% for car in car_list %}
      <li>
        <a href="{{ car.get_absolute_url }}">{{ car.car_model }}</a>  
        <a href="{{ car.get_absolute_url }}">({{ car.car_brand}})</a>
      </li>
      {% endfor %}

    </ul>

    {% else %}
      <p>TNo hay autos diponibles en este momento....</p>
    {% endif %}       

intake_site/catalog/templates/signup.html
{ extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}